language: csharp

os: linux # Ubuntu 14.04
dist: trusty
sudo: required
dotnet: 1.0.0-preview2-003121

services:
  - docker

script:
  - dotnet restore
  - dotnet build src/LclDckr
  - dotnet test test/LclDckr.IntegrationTests
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG ]]; then 
  dotnet pack src/LclDckr --configuration Release;
  nuget push src/LclDckr/bin/Release/*.nupkg -ApiKey $API_KEY;
  fi"
